# Generated by Django 5.1.6 on 2026-09-06 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_backfill_user_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='pending_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='pending_email_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
