# Generated by Django 5.1.6 on 2026-09-09 17:13

import accounts.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_pending_email_change'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('MANAGER', 'Manager'), ('RECRUITER', 'Recruiter'), ('CANDIDATE', 'Candidate')], default=accounts.enums.Role['CANDIDATE'], max_length=16),
        ),
    ]
