# Generated by Django 5.1.6 on 2026-08-23 04:45

import institutions.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nation', models.CharField(choices=[('ENGLAND', 'England'), ('SCOTLAND', 'Scotland'), ('WALES', 'Wales'), ('NORTHERN_IRELAND', 'Northern Ireland')], default=institutions.enums.Nation['ENGLAND'], max_length=32)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('institution_type', models.CharField(choices=[('UNIVERSITY', 'University'), ('COLLEGE', 'College'), ('CONSERVATOIRE', 'Conservatoire'), ('RESEARCH_INSTITUTE', 'Research institute'), ('BUSINESS_SCHOOL', 'Business school'), ('OTHER', 'Other')], default=institutions.enums.InstitutionType['UNIVERSITY'], max_length=32)),
                ('ranking', models.PositiveIntegerField(blank=True, help_text='Complete University Guide position, where ranked.', null=True)),
                ('website', models.URLField(blank=True, max_length=500)),
                ('careers_url', models.URLField(blank=True, max_length=500)),
                ('platform', models.CharField(choices=[('STONEFISH', 'Stonefish'), ('JOBTRAIN', 'Jobtrain'), ('COREHR', 'CoreHR'), ('EPLOY', 'eploy'), ('WORKDAY', 'Workday'), ('STRUCTURED', 'Structured data (JSON-LD or RSS)'), ('UNKNOWN', 'Unknown')], default=institutions.enums.Platform['UNKNOWN'], help_text='Detected on the last successful crawl.', max_length=32)),
                ('adapter_override', models.CharField(blank=True, choices=[('STONEFISH', 'Stonefish'), ('JOBTRAIN', 'Jobtrain'), ('COREHR', 'CoreHR'), ('EPLOY', 'eploy'), ('WORKDAY', 'Workday'), ('STRUCTURED', 'Structured data (JSON-LD or RSS)'), ('UNKNOWN', 'Unknown')], help_text='Set from the crawl console when detection picks the wrong adapter.', max_length=32)),
                ('crawl_enabled', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['crawl_enabled'], name='institution_crawl_e_0c2a09_idx'), models.Index(fields=['platform'], name='institution_platfor_6593ef_idx')],
            },
        ),
    ]
