# Generated by Django 5.1.6 on 2026-09-06 12:20

import institutions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0002_squashed_platform_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='banner',
            field=models.ImageField(blank=True, upload_to=institutions.models.institution_media_path),
        ),
        migrations.AddField(
            model_name='institution',
            name='description',
            field=models.TextField(blank=True, help_text="Plain text shown on the institution's page. Rendered as text, never as HTML."),
        ),
        migrations.AddField(
            model_name='institution',
            name='logo',
            field=models.ImageField(blank=True, upload_to=institutions.models.institution_media_path),
        ),
    ]
