# Generated by Django 5.1.6 on 2026-09-09 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_institution_branding'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='address',
            field=models.TextField(blank=True, help_text='Postal address, as it should be shown to a candidate.'),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='institution',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
