# Generated by Django 5.1.6 on 2026-09-09 17:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0004_institution_contact_details'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='recruiters',
            field=models.ManyToManyField(blank=True, related_name='assigned_institutions', to=settings.AUTH_USER_MODEL),
        ),
    ]
