# Generated by Django 5.1.6 on 2026-08-23 04:45

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import screening.enums
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        # pg_trgm backs step 3 of the sponsor matching cascade: the register holds legal
        # entity names that rarely match the everyday name exactly.
        TrigramExtension(),
        migrations.CreateModel(
            name='SponsorRegisterSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('downloaded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_url', models.URLField(max_length=500)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default profile', max_length=200)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('domains', models.JSONField(blank=True, default=list)),
                ('seniority', models.JSONField(blank=True, default=list)),
                ('projects', models.JSONField(blank=True, default=list)),
                ('education', models.JSONField(blank=True, default=list)),
                ('years_experience', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_profile')],
            },
        ),
        migrations.CreateModel(
            name='Ruleset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=200)),
                ('effective_from', models.DateField()),
                ('verified_at', models.DateField(help_text='When a human last checked these figures against the source.')),
                ('source_url', models.URLField(max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('is_active',), name='only_one_active_ruleset')],
            },
        ),
        migrations.CreateModel(
            name='JobScreening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sponsor_verdict', models.CharField(choices=[('CONFIRMED', 'Confirmed sponsor'), ('B_RATED', 'B-rated sponsor'), ('PROVISIONAL', 'Provisional sponsor'), ('CONFIRMED_VIA_PARENT', 'Confirmed via parent entity'), ('OTHER_ROUTE_ONLY', 'Licensed, but not for Skilled Worker'), ('NOT_FOUND', 'Not found on the register')], max_length=32)),
                ('sponsor_matched_name', models.CharField(blank=True, max_length=500)),
                ('sponsor_confidence', models.FloatField(default=0.0)),
                ('advert_excludes_sponsorship', models.BooleanField(default=False)),
                ('advert_exclusion_phrase', models.TextField(blank=True)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('salary_currency', models.CharField(default='GBP', max_length=3)),
                ('salary_period', models.CharField(choices=[('ANNUAL', 'Per annum'), ('MONTHLY', 'Per month'), ('WEEKLY', 'Per week'), ('DAILY', 'Per day'), ('HOURLY', 'Per hour'), ('UNKNOWN', 'Unstated')], default=screening.enums.SalaryPeriod['UNKNOWN'], max_length=16)),
                ('salary_confidence', models.CharField(choices=[('EXACT', 'Exact single figure'), ('PARSED', 'Range parsed cleanly'), ('LOW', 'Parsed, but incomplete'), ('UNPARSEABLE', 'Could not be parsed')], default=screening.enums.SalaryConfidence['UNPARSEABLE'], max_length=16)),
                ('threshold_verdict', models.CharField(choices=[('EXCLUDED_BELOW_FLOOR', 'Below personal floor'), ('PAY_CUT', 'Pay cut'), ('LATERAL_CONTINGENT', 'Lateral, contingent'), ('TARGET_BAND', 'Target band'), ('SALARY_UNCLEAR', 'Salary unclear')], max_length=32)),
                ('threshold_explanation', models.TextField(blank=True)),
                ('screened_on', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('general_threshold_met', models.BooleanField(null=True)),
                ('going_rate_met', models.BooleanField(null=True)),
                ('going_rate_key', models.CharField(blank=True, max_length=64)),
                ('fitness_score', models.PositiveSmallIntegerField(default=0)),
                ('fitness_reasons', models.JSONField(blank=True, default=list)),
                ('screened_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='screening', to='jobs.job')),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='screenings', to='screening.ruleset')),
            ],
            options={
                'indexes': [models.Index(fields=['sponsor_verdict'], name='screening_j_sponsor_6ca5e0_idx'), models.Index(fields=['threshold_verdict'], name='screening_j_thresho_b83cd9_idx'), models.Index(fields=['-fitness_score'], name='screening_j_fitness_aa4c9c_idx'), models.Index(fields=['salary_min'], name='screening_j_salary__e57575_idx')],
            },
        ),
        migrations.CreateModel(
            name='RulesetFigure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('transitional_general_threshold', 'Transitional general threshold'), ('standard_general_threshold', 'Standard general threshold'), ('soc_2134_going_rate', 'SOC 2134 - software developers'), ('soc_2139_going_rate', 'SOC 2139 - DevOps, IT consultants'), ('soc_2133_going_rate', 'SOC 2133 - BAs, architects, data engineers'), ('soc_2162_going_rate', 'SOC 2162 - researchers, RSE posts'), ('soc_3131_going_rate', 'SOC 3131 - RQF 3-5'), ('soc_3133_going_rate', 'SOC 3133 - RQF 3-5'), ('current_package', 'Current package'), ('personal_floor', 'Personal floor')], max_length=64)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('ruleset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='screening.ruleset')),
            ],
            options={
                'ordering': ['ruleset', 'key'],
                'constraints': [models.UniqueConstraint(fields=('ruleset', 'key'), name='unique_figure_per_ruleset')],
            },
        ),
        migrations.CreateModel(
            name='SponsorRegisterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organisation_name', models.CharField(max_length=500)),
                ('normalised_name', models.CharField(db_index=True, max_length=500)),
                ('town_city', models.CharField(blank=True, max_length=200)),
                ('county', models.CharField(blank=True, max_length=200)),
                ('type_rating', models.CharField(blank=True, max_length=300)),
                ('route', models.CharField(blank=True, max_length=300)),
                ('snapshot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='screening.sponsorregistersnapshot')),
            ],
            options={
                'verbose_name_plural': 'sponsor register entries',
                'indexes': [models.Index(fields=['snapshot', 'organisation_name'], name='screening_s_snapsho_f2385f_idx'), django.contrib.postgres.indexes.GinIndex(fields=['organisation_name'], name='sponsor_name_trgm', opclasses=['gin_trgm_ops'])],
            },
        ),
        migrations.CreateModel(
            name='InstitutionSponsorMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registered_legal_name', models.CharField(blank=True, max_length=500)),
                ('verdict', models.CharField(choices=[('CONFIRMED', 'Confirmed sponsor'), ('B_RATED', 'B-rated sponsor'), ('PROVISIONAL', 'Provisional sponsor'), ('CONFIRMED_VIA_PARENT', 'Confirmed via parent entity'), ('OTHER_ROUTE_ONLY', 'Licensed, but not for Skilled Worker'), ('NOT_FOUND', 'Not found on the register')], default=screening.enums.SponsorVerdict['NOT_FOUND'], max_length=32)),
                ('method', models.CharField(choices=[('EXACT', 'Exact name match'), ('NORMALISED', 'Normalised name match'), ('TRIGRAM', 'Trigram similarity'), ('HUMAN', 'Chosen by a human'), ('SEED', 'From the estate spreadsheet'), ('NONE', 'No match')], default=screening.enums.MatchMethod['NONE'], max_length=16)),
                ('confidence', models.FloatField(default=0.0)),
                ('candidates', models.JSONField(blank=True, default=list, help_text='Ranked register entries for a human to choose from, when nothing matched confidently enough to decide automatically.')),
                ('needs_review', models.BooleanField(default=False)),
                ('resolved_by_human', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_match', to='institutions.institution')),
                ('snapshot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='screening.sponsorregistersnapshot')),
            ],
            options={
                'verbose_name_plural': 'institution sponsor matches',
                'indexes': [models.Index(fields=['verdict'], name='screening_i_verdict_2779e2_idx'), models.Index(fields=['needs_review'], name='screening_i_needs_r_d5d8b9_idx')],
            },
        ),
    ]
