# Generated by Django 5.1.6 on 2026-08-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('screening', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='candidateprofile',
            options={'ordering': ['-is_active', 'name']},
        ),
    ]
