# Generated by Django 5.1.6 on 2026-09-06 13:26

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0003_institution_branding'),
        ('jobs', '0005_job_withdrawal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTermDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('term', models.CharField(max_length=64)),
                ('occurrences', models.PositiveIntegerField(default=0)),
                ('searchers', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-day', '-occurrences'],
                'indexes': [models.Index(fields=['-day', '-occurrences'], name='analytics_term_day_idx'), models.Index(fields=['term'], name='analytics_term_idx')],
                'constraints': [models.UniqueConstraint(fields=('day', 'term'), name='unique_term_per_day')],
            },
        ),
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SEARCH', 'Searched'), ('JOB_VIEW', 'Viewed a job'), ('JOB_SAVE', 'Saved a job'), ('JOB_UNSAVE', 'Unsaved a job'), ('APPLY', 'Recorded an application'), ('APPLICATION_MOVE', 'Moved an application'), ('INSTITUTION_VIEW', 'Viewed an institution'), ('CV_UPLOAD', 'Uploaded a CV'), ('EXPORT', 'Exported results')], max_length=24)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor_role', models.CharField(blank=True, max_length=16)),
                ('nation', models.CharField(blank=True, max_length=32)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('query', models.CharField(blank=True, max_length=200)),
                ('result_count', models.PositiveIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to=settings.AUTH_USER_MODEL)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='institutions.institution')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analytics_events', to='jobs.job')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['kind', '-occurred_at'], name='analytics_kind_time_idx'), models.Index(fields=['-occurred_at'], name='analytics_time_idx'), models.Index(fields=['institution', '-occurred_at'], name='analytics_inst_time_idx'), models.Index(fields=['actor', '-occurred_at'], name='analytics_actor_time_idx'), models.Index(fields=['actor_role', 'kind'], name='analytics_role_kind_idx')],
            },
        ),
    ]
