# Generated by Django 5.1.6 on 2026-08-23 04:45

import crawler.enums
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('MANUAL', 'Manual'), ('SCHEDULED', 'Scheduled')], default=crawler.enums.CrawlTrigger['MANUAL'], max_length=16)),
                ('status', models.CharField(choices=[('RUNNING', 'Running'), ('COMPLETE', 'Complete'), ('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed')], default=crawler.enums.CrawlRunStatus['RUNNING'], max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institutions_total', models.PositiveIntegerField(default=0)),
                ('institutions_done', models.PositiveIntegerField(default=0)),
                ('jobs_new', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('jobs_closed', models.PositiveIntegerField(default=0)),
                ('error_detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['status', '-started_at'], name='crawler_cra_status_407ef0_idx')],
            },
        ),
        migrations.CreateModel(
            name='RawResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cache_key', models.CharField(max_length=128, unique=True)),
                ('url', models.URLField(max_length=1000)),
                ('sha256', models.CharField(max_length=64)),
                ('status_code', models.PositiveSmallIntegerField(default=0)),
                ('content_type', models.CharField(blank=True, max_length=200)),
                ('etag', models.CharField(blank=True, max_length=300)),
                ('last_modified', models.CharField(blank=True, max_length=200)),
                ('byte_size', models.PositiveIntegerField(default=0)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('storage_path', models.CharField(max_length=500)),
            ],
            options={
                'ordering': ['-fetched_at'],
                'indexes': [models.Index(fields=['url', '-fetched_at'], name='crawler_raw_url_87b854_idx'), models.Index(fields=['fetched_at'], name='crawler_raw_fetched_cf4427_idx')],
            },
        ),
        migrations.CreateModel(
            name='CrawlRunInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adapter', models.CharField(blank=True, max_length=64)),
                ('outcome', models.CharField(choices=[('OK', 'OK'), ('ZERO_RESULTS', 'Zero results'), ('ROBOTS_DISALLOWED', 'Disallowed by robots.txt'), ('BLOCKED', 'Blocked'), ('OFFLINE', 'Site offline'), ('TIMEOUT', 'Timed out'), ('PARSE_ERROR', 'Parse error'), ('NO_ADAPTER', 'No adapter matched'), ('SKIPPED', 'Skipped')], max_length=32)),
                ('strategy', models.CharField(choices=[('JSON_LD', 'schema.org JSON-LD'), ('RSS', 'RSS feed'), ('JSON_API', 'JSON endpoint'), ('HTML', 'HTML selectors'), ('BROWSER_HTML', 'HTML rendered in a browser'), ('NONE', 'Nothing extracted')], default=crawler.enums.ExtractionStrategy['NONE'], max_length=32)),
                ('fallback_fired', models.BooleanField(default=False)),
                ('vacancies_found', models.PositiveIntegerField(default=0)),
                ('previous_vacancies_found', models.PositiveIntegerField(blank=True, null=True)),
                ('jobs_new', models.PositiveIntegerField(default=0)),
                ('jobs_updated', models.PositiveIntegerField(default=0)),
                ('jobs_closed', models.PositiveIntegerField(default=0)),
                ('duration_ms', models.PositiveIntegerField(default=0)),
                ('error_class', models.CharField(blank=True, max_length=120)),
                ('error_detail', models.TextField(blank=True)),
                ('raw_cache_keys', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_results', to='institutions.institution')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institution_results', to='crawler.crawlrun')),
            ],
            options={
                'ordering': ['institution__name'],
                'indexes': [models.Index(fields=['run', 'outcome'], name='crawler_cra_run_id_2848bb_idx'), models.Index(fields=['institution', '-started_at'], name='crawler_cra_institu_c8e427_idx')],
                'constraints': [models.UniqueConstraint(fields=('run', 'institution'), name='unique_institution_per_run')],
            },
        ),
    ]
