# Generated by Django 5.1.6 on 2026-08-24 05:38

import crawler.enums
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlrun',
            name='institution_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='crawlrun',
            name='status',
            field=models.CharField(choices=[('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('COMPLETE', 'Complete'), ('CANCELLED', 'Cancelled'), ('INCOMPLETE', 'Incomplete'), ('FAILED', 'Failed')], default=crawler.enums.CrawlRunStatus['RUNNING'], max_length=16),
        ),
        migrations.CreateModel(
            name='CrawlLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('ERROR', 'Error')], default=crawler.enums.CrawlLogLevel['INFO'], max_length=8)),
                ('message', models.TextField()),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('institution', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='institutions.institution')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='crawler.crawlrun')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['run', 'created_at'], name='crawler_cra_run_id_347a11_idx')],
            },
        ),
    ]
