# Generated by Django 5.1.6 on 2026-08-23 04:45

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
import jobs.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crawler', '0001_initial'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('FOUND', 'Found'), ('READY', 'Ready'), ('APPLIED', 'Applied'), ('ACKNOWLEDGED', 'Acknowledged'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('GHOSTED', 'Ghosted')], default=jobs.enums.ApplicationStatus['FOUND'], max_length=20)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('next_action', models.CharField(blank=True, max_length=300)),
                ('next_action_due', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('ghosted_flagged', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('query', models.CharField(help_text='The URL query string from the job list, stored verbatim so a saved search and a bookmarked URL can never drift apart.', max_length=2000)),
                ('digest_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'saved searches',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, choices=[('FOUND', 'Found'), ('READY', 'Ready'), ('APPLIED', 'Applied'), ('ACKNOWLEDGED', 'Acknowledged'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('GHOSTED', 'Ghosted')], max_length=20)),
                ('to_status', models.CharField(choices=[('FOUND', 'Found'), ('READY', 'Ready'), ('APPLIED', 'Applied'), ('ACKNOWLEDGED', 'Acknowledged'), ('INTERVIEW', 'Interview'), ('OFFER', 'Offer'), ('REJECTED', 'Rejected'), ('GHOSTED', 'Ghosted')], max_length=20)),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='jobs.application')),
            ],
            options={
                'ordering': ['occurred_at'],
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('PORTAL', 'Employer portal'), ('AGGREGATOR', 'Aggregator'), ('MANUAL', 'Added by hand')], default=jobs.enums.JobSource['PORTAL'], max_length=16)),
                ('source_url', models.URLField(max_length=1000)),
                ('title', models.CharField(max_length=500)),
                ('department', models.CharField(blank=True, max_length=300)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('description_html', models.TextField(blank=True)),
                ('description_text', models.TextField(blank=True)),
                ('location_raw', models.CharField(blank=True, max_length=300)),
                ('city', models.CharField(blank=True, max_length=120)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('salary_raw', models.CharField(blank=True, max_length=500)),
                ('grade_raw', models.CharField(blank=True, max_length=120)),
                ('contract_type', models.CharField(choices=[('PERMANENT', 'Permanent'), ('FIXED_TERM', 'Fixed term'), ('CASUAL', 'Casual'), ('SECONDMENT', 'Secondment'), ('UNKNOWN', 'Unstated')], default=jobs.enums.ContractType['UNKNOWN'], max_length=16)),
                ('hours', models.CharField(choices=[('FULL_TIME', 'Full time'), ('PART_TIME', 'Part time'), ('UNKNOWN', 'Unstated')], default=jobs.enums.Hours['UNKNOWN'], max_length=16)),
                ('workplace', models.CharField(choices=[('ON_SITE', 'On site'), ('HYBRID', 'Hybrid'), ('REMOTE', 'Remote'), ('UNKNOWN', 'Unstated')], default=jobs.enums.Workplace['UNKNOWN'], max_length=16)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('DISAPPEARED', 'No longer listed'), ('CLOSED', 'Closed')], default=jobs.enums.JobStatus['OPEN'], max_length=16)),
                ('first_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_seen_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('disappeared_at', models.DateTimeField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, max_length=64)),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='institutions.institution')),
            ],
            options={
                'ordering': ['-posted_date', '-first_seen_at'],
            },
        ),
        migrations.AddField(
            model_name='application',
            name='job',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='jobs.job'),
        ),
        migrations.CreateModel(
            name='JobRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('title', 'Title'), ('salary_raw', 'Salary'), ('closing_date', 'Closing date'), ('description_text', 'Description'), ('location_raw', 'Location'), ('status', 'Status')], max_length=32)),
                ('value_before', models.TextField(blank=True)),
                ('value_after', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('crawl_run', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisions', to='crawler.crawlrun')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='jobs.job')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('saved_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='saved', to='jobs.job')),
            ],
            options={
                'ordering': ['-saved_at'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['institution', 'status'], name='jobs_job_institu_0f3fcd_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['closing_date'], name='jobs_job_closing_769c0f_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['posted_date'], name='jobs_job_posted__0a7770_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', '-posted_date'], name='jobs_job_status_7d54d0_idx'),
        ),
        migrations.AddIndex(
            model_name='job',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='job_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='job',
            constraint=models.UniqueConstraint(fields=('institution', 'source_url'), name='unique_job_per_institution_url'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['status'], name='jobs_applic_status_f83260_idx'),
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['next_action_due'], name='jobs_applic_next_ac_a94f37_idx'),
        ),
        migrations.AddIndex(
            model_name='jobrevision',
            index=models.Index(fields=['job', '-changed_at'], name='jobs_jobrev_job_id_c29a14_idx'),
        ),
    ]
