# Generated by Django 5.1.6 on 2026-08-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedsearch',
            name='query',
            field=models.CharField(blank=True, help_text="The URL query string from the job list, stored verbatim so a saved search and a bookmarked URL can never drift apart. Blank means 'everything new', which is a legitimate thing to want in a digest.", max_length=2000),
        ),
    ]
