"""Give saved jobs, applications and saved searches an owner.

Written by hand rather than autogenerated because the column cannot go straight to ``NOT NULL``:
existing rows have no owner yet. Nullable, backfill, then tighten — all inside one transaction,
so there is no window where the constraint is missing on a live table.
"""

from __future__ import annotations

from typing import Any

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

from jobs.migrations._0004_helpers import sole_owner

_OWNED = ("savedjob", "application", "savedsearch")


def assign_owner(apps: Any, schema_editor: Any) -> None:
    """Point every existing row at the sole account, if there are any rows at all."""
    has_rows = any(apps.get_model("jobs", model).objects.exists() for model in _OWNED)
    if not has_rows:
        return

    owner = sole_owner(apps)
    for model in _OWNED:
        apps.get_model("jobs", model).objects.filter(owner__isnull=True).update(owner=owner)


def clear_owner(apps: Any, schema_editor: Any) -> None:
    """Drop the owner again, so the migration reverses cleanly."""
    for model in _OWNED:
        apps.get_model("jobs", model).objects.update(owner=None)


def _owner_field(*, null: bool, related_name: str) -> models.ForeignKey:
    return models.ForeignKey(
        null=null,
        on_delete=django.db.models.deletion.CASCADE,
        related_name=related_name,
        to=settings.AUTH_USER_MODEL,
    )


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("jobs", "0003_job_category"),
    ]

    operations = [
        # 1. Nullable, so existing rows survive the column being added.
        migrations.AddField("savedjob", "owner", _owner_field(null=True, related_name="saved_jobs")),
        migrations.AddField(
            "application", "owner", _owner_field(null=True, related_name="applications")
        ),
        migrations.AddField(
            "savedsearch", "owner", _owner_field(null=True, related_name="saved_searches")
        ),
        # 2. Fill them in.
        migrations.RunPython(assign_owner, clear_owner),
        # 3. Now the column can be required.
        migrations.AlterField(
            "savedjob", "owner", _owner_field(null=False, related_name="saved_jobs")
        ),
        migrations.AlterField(
            "application", "owner", _owner_field(null=False, related_name="applications")
        ),
        migrations.AlterField(
            "savedsearch", "owner", _owner_field(null=False, related_name="saved_searches")
        ),
        # 4. One row per job becomes one row per (owner, job). The related_name changes too, so
        #    any missed `job.saved` / `job.application` raises instead of answering wrongly.
        migrations.AlterField(
            "savedjob",
            "job",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="saved_by", to="jobs.job"
            ),
        ),
        migrations.AlterField(
            "application",
            "job",
            models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="applications",
                to="jobs.job",
            ),
        ),
        migrations.AlterField("savedsearch", "name", models.CharField(max_length=120)),
        migrations.AddConstraint(
            "savedjob",
            models.UniqueConstraint(fields=["owner", "job"], name="unique_saved_job_per_owner"),
        ),
        migrations.AddConstraint(
            "application",
            models.UniqueConstraint(fields=["owner", "job"], name="unique_application_per_owner"),
        ),
        migrations.AddConstraint(
            "savedsearch",
            models.UniqueConstraint(
                fields=["owner", "name"], name="unique_saved_search_name_per_owner"
            ),
        ),
        migrations.AddIndex(
            "savedjob", models.Index(fields=["owner"], name="jobs_savedjob_owner_idx")
        ),
        migrations.AddIndex(
            "application",
            models.Index(fields=["owner", "status"], name="jobs_app_owner_status_idx"),
        ),
    ]
