# Generated by Django 5.1.6 on 2026-09-06 01:46

import django.db.models.deletion
import jobs.enums
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_multi_tenant_ownership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='withdrawn_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='withdrawn_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawn_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='withdrawn_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('DISAPPEARED', 'No longer listed'), ('CLOSED', 'Closed'), ('WITHDRAWN', 'Withdrawn by an administrator')], default=jobs.enums.JobStatus['OPEN'], max_length=16),
        ),
    ]
