# Generated by Django 5.1.6 on 2026-09-06 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='contract_raw',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='job',
            name='hours_raw',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
