# Generated by Django 5.1.6 on 2026-09-09 14:10

import jobs.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_keeps_contract_and_hours_raw'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='discipline',
            field=models.CharField(choices=[('AGRICULTURE_FOOD_VETERINARY', 'Agriculture, Food & Veterinary'), ('ARCHITECTURE_BUILDING_PLANNING', 'Architecture, Building & Planning'), ('BIOLOGICAL_SCIENCES', 'Biological Sciences'), ('BUSINESS_MANAGEMENT_STUDIES', 'Business & Management Studies'), ('COMPUTER_SCIENCES', 'Computer Sciences'), ('CREATIVE_ARTS_DESIGN', 'Creative Arts & Design'), ('ECONOMICS', 'Economics'), ('EDUCATION_STUDIES', 'Education Studies'), ('ENGINEERING_TECHNOLOGY', 'Engineering & Technology'), ('HEALTH_MEDICAL', 'Health & Medical'), ('HISTORICAL_PHILOSOPHICAL_STUDIES', 'Historical & Philosophical Studies'), ('INFORMATION_MANAGEMENT_LIBRARIANSHIP', 'Information Management & Librarianship'), ('LANGUAGES_LITERATURE_CULTURE', 'Languages, Literature & Culture'), ('LAW', 'Law'), ('MATHEMATICS_STATISTICS', 'Mathematics & Statistics'), ('MEDIA_COMMUNICATIONS', 'Media & Communications'), ('PHYSICAL_ENVIRONMENTAL_SCIENCES', 'Physical & Environmental Sciences'), ('POLITICS_GOVERNMENT', 'Politics & Government'), ('PSYCHOLOGY', 'Psychology'), ('SOCIAL_SCIENCES_SOCIAL_CARE', 'Social Sciences & Social Care'), ('ADMINISTRATIVE', 'Administrative'), ('ESTATES_FACILITIES_MANAGEMENT', 'Estates & Facilities Management'), ('FINANCE_PROCUREMENT', 'Finance & Procurement'), ('FUNDRAISING_ALUMNI_BIDS_GRANTS', 'Fundraising, Alumni, Bids & Grants'), ('HEALTH_WELLBEING_CARE', 'Health, Wellbeing & Care'), ('HOSPITALITY_RETAIL_EVENTS', 'Hospitality, Retail, Conferences & Events'), ('HUMAN_RESOURCES', 'Human Resources'), ('INTERNATIONAL_ACTIVITIES', 'International Activities'), ('IT_SERVICES', 'IT Services'), ('LABORATORY_CLINICAL_TECHNICIAN', 'Laboratory, Clinical & Technician'), ('LEGAL_COMPLIANCE_POLICY', 'Legal, Compliance & Policy'), ('LIBRARY_SERVICES_DATA_INFORMATION', 'Library Services, Data & Information Management'), ('PR_MARKETING_SALES_COMMUNICATION', 'PR, Marketing, Sales & Communication'), ('PROJECT_MANAGEMENT_CONSULTING', 'Project Management & Consulting'), ('SENIOR_MANAGEMENT', 'Senior Management'), ('STUDENT_SERVICES', 'Student Services'), ('SUSTAINABILITY', 'Sustainability'), ('WEB_DESIGN_DEVELOPMENT', 'Web Design & Development'), ('SPORT_LEISURE', 'Sport & Leisure'), ('STUDENTSHIPS_PHDS', 'Studentships & PhDs'), ('OTHER', 'Other')], default=jobs.enums.Discipline['OTHER'], max_length=48),
        ),
    ]
